import { readFileSync, writeFileSync } from 'node:fs';
const families = ['reptiles', 'mammals', 'aquatic', 'birds', 'prehistoric', 'mystical', 'eggs', 'babies', 'teens'];
const art = families.map(f => readFileSync(`js/creatures/${f}.js`, 'utf8')).join('\n');
writeFileSync('src/creature-art.js', '// Original Scribbies artwork, adapted as an ES module. Generated by scripts/prepare-art.mjs.\n' + art + '\nexport {renderAdultMammal,renderAdultReptile,renderAdultAquatic,renderAdultBird,renderAdultPrehistoric,renderAdultMystical,renderEgg,renderBaby,renderTeen};\n');

// Reuse the original animation definitions without carrying its old UI styles.
const old = readFileSync('classic.html', 'utf8') + readFileSync('css/styles.css','utf8');
const blocks=[]; const re=/@keyframes\s+[\w-]+\s*\{/g; let m;
while((m=re.exec(old))){let depth=1,i=re.lastIndex;for(;i<old.length&&depth;i++){if(old[i]==='{')depth++;if(old[i]==='}')depth--;}blocks.push(old.slice(m.index,i));re.lastIndex=i;}
writeFileSync('src/legacy-animations.css',[...new Set(blocks)].join('\n'));
