import {readFileSync,writeFileSync} from 'node:fs';
const replacements=[
 ['Faith grows here','Woodland habitat'],['Kindness makes a home','Riverside habitat'],['Find your brave','Nightfall habitat'],
 ['A little faith. A big adventure.','Learn. Hatch. Explore.'],['Your little world','Your world'],['YOUR LITTLE WORLD','YOUR WORLD'],
 ['A little adventure, every day.','Your next adventure starts here.'],['Grow your faith. Find your friends. See where the path leads.','Practice a verse. Raise your Scribbies. Explore the world.'],
 ['WONDER IS WAITING','READY TO EXPLORE?'],['A little faith','The first trail'],
 ['Little beginnings','New explorer'],['A little light for your day','Today’s verse'],['A LITTLE LIGHT FOR YOUR DAY','TODAY’S VERSE'],
 ['A tiny egg. A world of possibility.','Your first egg is waiting.'],['Every verse makes me a little warmer.','Practice to help me hatch.'],['Every adventure is better together!','Ready when you are!'],
 ['Your little beginning','Your Scribby egg'],['A very special egg','Your Scribby egg'],['Your first friend is waiting','Choose your first egg'],['Choose an egg. Begin something wonderful.','Keep it warm. See who hatches.'],
 ['Little wins today','Daily goals'],['A little treasure awaits','Daily reward'],['Your treasure is collected!','Reward collected'],
 ['Every verse you learn brings<br>a new friendship a little closer.','Explore trails to discover more eggs.<br>Raise each one at your own pace.'],
 ['Look how far you’ve come!','Chapter complete!'],['A whole new chapter is waiting for you.','The next chapter is unlocked.'],
 ['A little warmth, a little wonder','Practice to build warmth'],['6 little discoveries','6 discoveries'],
 ['SO MANY LITTLE PERSONALITIES','FIELD GUIDE'],['Your little family','Your Scribbies'],
 ['WORDS TO KEEP IN YOUR HEART','YOUR LIBRARY'],['Little by little, these words become a part of you.','Pick a verse, choose a practice mode, and track your progress.'],
 ['A little practice goes a long way.','Build your memory, one verse at a time.'],['verses are\'} ready for a little review.','verses are\'} ready to review.'],
 ['HOME IS WHERE YOUR SCRIBBY IS','CAMP'],['’s little corner.','’s camp.'],['Learn together. Play together. Grow a little closer.','Feed, play, and practice to help your Scribby grow.'],
 ['Your little family','Your Scribbies'],['Your little ','Your '],['a little egg','an egg'],['A little egg','An egg'],
 ['Your very own baby Scribby.','Your Scribby has hatched!'],['Learn, feed, and play together. A beautiful friendship starts right here.','Name your new buddy. Then feed, play, and practice to help it grow.'],
 ['Every friendship starts somewhere.','Choose your first egg'],['Three little eggs. One is waiting just for you. Practice scriptures to keep it warm, then meet the friend inside.','Choose a habitat egg. Scripture practice builds warmth. At 60 warmth, your egg is ready to hatch.'],
 ['The meadow egg','Meadow egg'],['The tidepool egg','Tidepool egg'],['The blossom egg','Blossom egg'],
 ['Warm, brave, and full of possibility.','A woodland Scribby is growing inside.'],['A little ripple of curiosity.','Home to a curious waterside Scribby.'],['A kind heart is growing inside.','A friendly woodland Scribby awaits.'],
 ['This is my little egg','Choose this egg'],['A little friend is ready for a very big hello.','Your egg is ready. Tap below to hatch it.'],
 ['A fresh little beginning. Your new egg is waiting.','New adventure started. Choose your egg.'],
 ['A little moment for a grown-up','Ask a grown-up'],['A little care behind the scenes.','Family settings'],['Make Scribbies feel right for your family.','Manage your profile, settings, and backups.'],
 ['Little game sounds','Game sounds'],['Gentle chimes and celebrations','Chimes and celebrations'],['A little guide to your adventure','How to play'],['A little time to learn','Scripture practice'],
 ['A little game with ','Memory match with '],['Remember our little pattern.','Remember the pattern.'],['our little pattern','the pattern'],
 ['A little extra personality!','Charm equipped.'],['A LITTLE EXTRA PERSONALITY','CUSTOMIZE'],
 ['A little growth spurt! Your Scribby has a new life stage.','Your Scribby grew! Check out its new life stage.'],
 ['A little help','Hint'],['A little hint','Show a hint'],['Little hints','First-letter hints'],['little gaps','gaps'],['little gap','gap'],
 ['Little challenge','Challenge'],['Little step','Step'],['little challenge','challenge'],['little step','step'],
 ['Let’s learn a little verse.','Read the verse.'],['FIRST, GET TO KNOW THE WORDS','READ & LISTEN'],
 ['Your egg is listening','Your egg'],['Let’s warm your little egg.','This practice warms your egg.'],
 ['A peaceful moment to learn together.','Practice with your Scribby.'],['Next little step','Next challenge'],['That’s it. Beautifully remembered!','Correct. You’ve got it!'],
 ['One little step closer.','Ready for the next challenge?'],['You’re learning. Let’s try that again.','Not quite. Give it another try.'],
 ['Small steps count. Your Scribby is cheering for you.','No timer. Hints and retries are always available.'],
 ['LOOK WHAT YOU DID','PRACTICE COMPLETE'],['A whole chapter of courage.','You earned a chapter badge!'],
 ['A new little beginning!','You found a new egg!'],['A little wiser. A little closer.','Nice work. Rewards earned.'],
 ['a precious egg. Raise it with love.','an egg to raise at camp.'],['You made time for something good. Your Scribby felt it, too.','Your practice helped your Scribby grow.'],
 ['A lovely step forward. Come back another day to help it stick.','Review another day to strengthen your memory.'],
 ['You kept trying. That’s how learning grows.','Keep practicing. You can use fewer hints next time.'],
 ['Start a new little adventure?','Start a new adventure?'],['Save this little adventure for later?','Leave this practice?'],
 ['That little step didn’t work. Please try again.','That action didn’t work. Please try again.'],
 ['A name for your little friend','Rename your Scribby'],['A lovely name for an explorer.','Nickname saved.'],
 ['Your words have a home in the journal.','Verse saved.'],['Words your family loves','Add a verse or quote'],
 ['A little treasure! +40 leaves and 2 berries.','Daily reward: +40 leaves and 2 berries.'],
 ['Little beginnings','New explorer'],['A little light that grows with every act of faith, courage, and love.','Protects the Everlight tree. Its antlers glow when a new egg is ready to hatch.'],
 ['You make my little world brighter.','Happy to see you!'],['A happy little hello!','Your Scribby says hello!'],['Mmm! That was berry, berry good.','That was delicious!'],
 ['Your egg gives a tiny, hopeful wiggle.','Your egg gives a wiggle.'],['Say it together.','Say it out loud.']
];
for(const path of ['src/app.js','src/views.js','src/data.js','src/game.js','index.html']){let text=readFileSync(path,'utf8');for(const [a,b] of replacements)text=text.split(a).join(b);writeFileSync(path,text)}
