import {SPECIES,CHARMS,speciesById} from './data.js';
import {activeBuddy,growthInfo,stage,dailyDone} from './game.js';
import {buddyArt,button,progress,escape as e} from './ui.js';
import {icon} from './icons.js';

const tool=(label,symbol,action,extra='')=>`<button class="pet-tool" data-action="${action}" ${extra}><span>${icon(symbol)}</span><b>${label}</b></button>`;
export function home(s){
 const b=activeBuddy(s),egg=!b?.hatched,ready=egg&&b?.warmth>=60,g=growthInfo(b);
 const name=egg?'Your egg':e(b.name);
 const hint=ready?'Ready to hatch!':egg?'Learn a verse to help me hatch.':'Tap to say hello.';
 return `<section class="pet-home" aria-label="Your Scribby’s home"><header class="pet-header"><span class="pet-brand"><img src="./icon.svg" alt=""/>scribbies</span><div class="pet-header-actions"><button class="pet-wallet" data-action="shop" aria-label="Shop. ${s.coins} leaves">${icon('leaf')} ${s.coins}</button><button class="icon-btn" data-action="audio" aria-label="Music and sound">${icon('volume')}</button><button class="icon-btn" data-action="home-menu" aria-label="More options">${icon('menu')}</button></div></header><nav class="pet-tools" aria-label="Your things">${tool('Food','berry','food')}${tool('Dress up','shirt','wardrobe')}${tool('Scribbies','paw','nursery')}${tool('Explore','compass','adventure')}</nav><div class="pet-habitat" id="camp-scene"><div class="pet-title"><button data-action="${egg?'growth':'rename'}" aria-label="${egg?'Egg growth':'Rename '+e(b.name)}"><h1>${name}</h1>${egg?'':icon('edit')}</button><span>${egg?'Egg':{baby:'Baby',teen:'Young',adult:'Grown',radiant:'Radiant'}[stage(b)]}</span></div><div class="pet-stage"><p class="pet-prompt" id="camp-speech" aria-live="polite">${hint}</p><button class="camp-creature ${ready?'hatch-ready':''}" data-action="${!b?'choose':ready?'crack-egg':egg?'warm':'pet'}" aria-label="${ready?'Hatch your egg':egg?'Warm your egg':'Say hello to '+e(b.name)}">${buddyArt(b,280)}</button></div><button class="pet-growth" data-action="growth" aria-label="${egg?'Egg warmth':'Growth'} ${g.value} of ${g.max}. See growth stages"><span>${icon(egg?'sun':'paw')} ${ready?'Tap your egg to hatch':egg?'Warmth':g.next==='Best friends'?'Growth':'Growing'}<b>${g.value} / ${g.max}</b></span>${progress(g.value,g.max,'',egg?'Egg warmth':'Growth')}</button></div><nav class="pet-care" aria-label="Care and learning">${tool(egg?'Warm':'Feed',egg?'sun':'berry',egg?'warm':'feed')}${tool('Play','puzzle','play')}${tool(ready?'Hatch':'Learn',ready?'sparkles':'book',ready?'crack-egg':'home-learn')}</nav></section>`;
}
export function foodShelf(s){const b=activeBuddy(s);return `<div class="home-item"><span class="home-item-icon food-icon">${icon('berry')}</span><div><h3>Berries <span>× ${s.berries}</span></h3><p>${b?.hatched?'A snack for '+e(b.name)+'.':'A snack for hatching day.'}</p></div>${button('Feed','shelf-feed','primary',!b?.hatched||!s.berries?'disabled':'')}</div><div class="home-item"><span class="home-item-icon">${icon('gift')}</span><div><h3>3 berries</h3><p>${icon('leaf')} 12 leaves</p></div>${button('Buy','buy-berries','secondary',s.coins<12||s.berries>9996?'disabled':'')}</div><p class="modal-footnote">You also earn berries by learning.</p>`}
export function wardrobe(s){const b=activeBuddy(s);return `<p class="shop-balance">${icon('leaf')} ${s.coins} leaves</p>${!b?.hatched?'<p class="modal-intro">Pick something for hatching day.</p>':''}<div class="charm-grid home-charms">${CHARMS.map(c=>`<button class="charm-card ${b?.charm===c.id?'selected':''}" data-charm="${c.id}" aria-pressed="${b?.charm===c.id}"><span class="charm-preview" style="background:${c.color}">${icon(c.icon)}</span><strong>${c.name}</strong><small>${b?.charm===c.id?'Selected':s.charms.includes(c.id)?'Wear':`${c.cost} leaves`}</small></button>`).join('')}</div>`}
export function nursery(s){return `<div class="nursery-list">${s.buddies.map(b=>`<button class="nursery-item ${b.id===s.active?'selected':''}" data-buddy="${b.id}">${buddyArt(b,70)}<span><strong>${b.hatched?e(b.name):e(speciesById(b.id).name)+' egg'}</strong><small>${b.hatched?growthInfo(b).label:'Egg · '+b.warmth+'/60 warmth'}</small></span>${b.id===s.active?icon('check'):icon('chevron')}</button>`).join('')}</div><button class="btn outline wide" data-view="collection">${icon('paw')} All ${SPECIES.length} Scribbies</button>`}
export function growthDetails(s){const b=activeBuddy(s),g=growthInfo(b);return `<div class="growth-detail">${buddyArt(b,145)}<h3>${b?.hatched?e(b.name):'Your egg'}</h3><p>${b?.hatched?'Feed, play, and learn to grow.':'Learning adds warmth. At 60, tap your egg to hatch.'}</p>${progress(g.value,g.max)}<div class="growth-stages">${[['egg','Egg'],['baby','Baby'],['teen','Young'],['adult','Grown'],['radiant','Radiant']].map(([id,name])=>`<span class="${id===stage(b)?'current':''}">${icon(id==='egg'?'sun':id==='radiant'?'sparkles':'paw')}${name}</span>`).join('')}</div>${button(b?.hatched?'Learn together':'Learn a verse','home-learn','primary wide')}</div>`}
export function homeMenu(s){return `<div class="home-menu">${[['journal','book','Verses'],['goals','gift',dailyDone(s).every(Boolean)&&!s.daily.claimed?'Collect reward':'Daily goals'],['help','help','How to play'],['parent','settings','Grown-up settings']].map(([action,i,label])=>`<button data-action="${action}">${icon(i)}<strong>${label}</strong>${icon('chevron')}</button>`).join('')}</div>`}
