import {home} from './home.js';
import {SPECIES,REGIONS,POSITIONS,VERSES,MODES,CHARMS,speciesById,nodeId} from './data.js';
import {activeBuddy,growthInfo,level,nodeUnlocked,regionUnlocked,nextNode,dailyDone,dueVerses,stage,dayKey} from './game.js';
import {icon} from './icons.js';
import {art,eggArt,buddyArt,button,progress,escape as e} from './ui.js';
const nav=[['adventure','compass','Adventure'],['collection','paw','Scribbypedia'],['camp','tent','My camp'],['journal','book','Verse journal']];
export const heading=(eyebrow,title,description,aside='')=>`<div class="page-heading"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${description}</p></div>${aside}</div>`;
export function shell(s,view,content,region){
 if(view==='home')return `<a class="skip-link" href="#main-content">Skip to game</a><main id="main-content" class="pet-main" tabindex="-1">${content}</main>`;
 const titles={adventure:'Explore',collection:'Scribbies',camp:'Home',journal:'Verses',settings:'Grown-up settings',practice:'Learn'};
 const navigation=[['home','home','Home'],['adventure','compass','Explore'],['collection','paw','Scribbies'],['journal','book','Verses']];
 return `<a class="skip-link" href="#main-content">Skip to game</a><div class="app-body game-body"><header class="topbar"><button class="btn ghost" data-view="home">${icon('back')} Home</button><strong>${titles[view]||'Scribbies'}</strong><span class="currency coins" aria-label="${s.coins} leaves">${icon('leaf')} ${s.coins}</span><button class="icon-btn" data-action="audio" aria-label="Music and sound">${icon('volume')}</button></header><main id="main-content" tabindex="-1">${content}</main>${view==='practice'?'':`<nav class="mobile-nav" aria-label="Main navigation">${navigation.map(([id,i,n])=>`<button data-view="${id}" class="${view===id?'active':''}" ${view===id?'aria-current="page"':''}>${icon(i)}<span>${n}</span></button>`).join('')}</nav>`}</div>`;
}
export function dailyCard(s){const done=dailyDone(s);return `<section class="daily-card"><div class="section-line"><h2>Daily goals</h2><span>${done.filter(Boolean).length} / 3</span></div>${['Take a scripture adventure','Care for your egg or buddy','Finish 3 learning sessions'].map((t,i)=>`<div class="daily-task"><span class="task-check ${done[i]?'complete':''}">${done[i?i:0]?icon('check'):''}</span><span>${t}</span>${i===2?`<b>${Math.min(3,s.daily.practices)}/3</b>`:''}</div>`).join('')}<div class="daily-reward">${icon('gift')}<div><strong>${s.daily.claimed?'Reward collected':'Daily reward'}</strong><span>40 leaves + 2 berries${!s.buddies.some(b=>b.id==='fern')?' + a Fern egg':''}</span></div>${s.daily.claimed?icon('check'):done.every(Boolean)?button('Open','daily','secondary'):icon('lock')}</div></section>`}
export function companionCard(s){const b=activeBuddy(s);const g=growthInfo(b);return `<section class="companion-card"><div class="section-line"><h2>${!b||!b.hatched?'Your Scribby egg':'Your adventure buddy'}</h2>${icon('heart')}</div><div class="buddy-stage">${buddyArt(b,200)}<span class="speech-bubble">${!b?'Your first egg is waiting.':!b.hatched?b.warmth>=60?'Tap, tap… someone is ready!':'Practice to help me hatch.':'Ready when you are!'}</span></div><h3>${b?(b.hatched?e(b.name):'Your Scribby egg'):'Choose your first egg'}</h3><p>${b?(b.hatched?`${speciesById(b.id).family} · ${g.label}`:g.label):'Keep it warm. See who hatches.'}</p>${b?`<div class="buddy-progress"><span>${b.hatched?'Growth':'Warmth'} <b>${g.value} / ${g.max}</b></span>${progress(g.value,g.max,'',b.hatched?'Companion growth':'Egg warmth')}</div>`:''}${button(`${!b?'Choose my egg':!b.hatched&&b.warmth>=60?'Hatch my egg':'Visit my camp'} ${icon(!b?'sparkles':!b.hatched&&b.warmth>=60?'heart':'tent')}`,!b?'choose':!b.hatched&&b.warmth>=60?'hatch':'camp','secondary')}</section>`}
export function adventure(s,r){const region=REGIONS[r],next=nextNode(s,r),verse=VERSES[r*6+next];const complete=Object.keys(s.completed).filter(k=>k.startsWith(`${r}-`)).length;
 return heading('READY TO EXPLORE?',s.buddies.length?'Explore':'Explore','Follow a trail to find new eggs.',`<span class="chapter-pill">${icon(region.icon)} Chapter 0${r+1} / 03</span>`)+`<div class="adventure-grid"><section class="journey-column"><div class="region-tabs" role="group" aria-label="Chapters">${REGIONS.map((region,i)=>`<button data-region="${i}" class="region-tab ${r===i?'selected':''}" aria-pressed="${r===i}">${icon(regionUnlocked(s,i)?region.icon:'lock')} ${region.name}</button>`).join('')}</div><section class="world-card region-${r}"><div class="world-caption"><span class="eyebrow">${region.label}</span><h2>${region.name}</h2><span>${icon(region.icon)} ${region.theme}</span></div><div class="map-scene"><img class="map-art" src="./assets/meadow-map.webp" alt="A winding woodland path with a cottage, a stream, and a glowing tree"/>${POSITIONS.map(([x,y],i)=>{const saved=s.completed[nodeId(r,i)],unlocked=nodeUnlocked(s,r,i);return `<button data-node="${i}" class="map-node ${saved?'done':unlocked?'current':'locked'}" style="left:${x}%;top:${y}%" aria-label="Stop ${i+1}: ${region.nodes[i]}. ${saved?'Complete, '+saved.stars+' stars':unlocked?'Ready to explore':'Locked'}"><span>${saved?icon('check'):icon(unlocked?'paw':'lock')}</span>${!saved&&unlocked?`<b>${s.buddies.length?'EXPLORE HERE':'START HERE'}</b>`:''}${saved?`<small aria-hidden="true">${'★'.repeat(saved.stars)}</small>`:''}</button>`}).join('')}<div class="fireflies" aria-hidden="true">${Array.from({length:6},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div></div><div class="world-footer"><span>${icon('compass')} ${complete} / 6 discoveries</span><span>${icon('medal')} ${complete===6?'Earned: ':''}The ${region.badge} badge</span></div></section><section class="next-adventure"><div class="quest-symbol">${icon(complete===6?'medal':'compass')}</div><div><span class="eyebrow">${complete===6?'CHAPTER COMPLETE':'YOUR NEXT ADVENTURE'}</span><h3>${complete===6?'Chapter complete!':region.nodes[next]}</h3><p>${complete===6?r<2?'The next chapter is unlocked.':'The Everlight shines. Your adventure keeps growing.':!s.active?'Choose an egg, then follow the path.':verse.ref+' · '+verse.topic}</p><div class="quest-tags"><span>${icon('clock')} About 3 min</span><span>${icon('sparkles')} +45 XP</span><span>${icon('paw')} ${r===0&&next===0?'Warm your egg':'Discover a friend'}</span></div></div>${button(`${complete===6&&r<2?'Next chapter':'Let’s explore'} ${icon('arrow')}`,complete===6&&r<2?'next-region':'start')}</section><div class="thought-card">${icon('book')}<div><span class="eyebrow">TODAY’S VERSE</span><p>“${e(verse.text)}”</p><span>${verse.ref} · KJV</span></div></div></section><aside class="companion-column">${companionCard(s)}${dailyCard(s)}<div class="discovery-note">${icon('sparkles')}<p>Explore trails to discover more eggs.<br>Raise each one at your own pace.</p></div></aside></div>`;
}
export function collection(s,family='All',owned=false){const creatures=SPECIES.filter(sp=>(family==='All'||sp.family===family)&&(!owned||s.buddies.some(b=>b.id===sp.id)));return heading('FIELD GUIDE','Your Scribbypedia',`${s.buddies.length} of ${SPECIES.length} friends discovered. Every one has a story.`)+`<div class="toolbar"><div class="filter-chips" role="group" aria-label="Creature families">${['All','Woodland','Waterside','Skyfolk','Ancients','Starlight'].map(f=>`<button data-family="${f}" class="chip ${family===f?'selected':''}" aria-pressed="${family===f}">${f}</button>`).join('')}</div><label class="check-label"><input id="owned-filter" type="checkbox" ${owned?'checked':''}> My Scribbies</label></div><div class="collection-grid">${creatures.map(sp=>{const b=s.buddies.find(b=>b.id===sp.id);return `<button class="species-card ${b?'discovered':'undiscovered'}" data-species="${sp.id}" style="--species-bg:${sp.color}"><div class="species-meta"><span>No. ${String(SPECIES.indexOf(sp)+1).padStart(3,'0')}</span>${b?.id===s.active?`<span class="active-label">${icon('heart')} Buddy</span>`:icon(b?'check':'lock')}</div><div class="species-art">${b?buddyArt(b,165):`<div class="mystery-art">${icon('paw')}<span>?</span></div>`}</div><div class="species-info"><span class="rarity ${sp.rarity.toLowerCase()}">${sp.rarity}</span><h3>${b?e(b.hatched?b.name:sp.name+' egg'):'???'}</h3><p>${sp.family} · ${b?(b.hatched?growthInfo(b).label:'Waiting to hatch'):'Undiscovered'}</p></div></button>`}).join('')}</div>${creatures.length?'':`<div class="empty-state">${icon('paw')}<h2>No friends here just yet.</h2><p>Try another family, or explore a new trail.</p>${button('Explore the woods','adventure')}</div>`}`}
export const camp=home;
export const masteryLabel=m=>['New','Learning','Familiar','Growing','Confident','Mastered'][m];
export function journal(s,search='',topic='All'){const list=s.verses.filter(v=>(topic==='All'||topic==='Review'&&dueVerses(s).some(d=>d.id===v.id)||v.topic===topic)&&`${v.ref} ${v.text} ${v.topic}`.toLowerCase().includes(search.toLowerCase()));const due=dueVerses(s);return heading('YOUR LIBRARY','Your verse journal','Pick a verse, choose a practice mode, and track your progress.',button(`${icon('plus')} Add a verse`,'add-verse','primary'))+`<section class="review-banner"><span class="review-icon">${icon('book')}</span><div><h2>${due.length?`${due.length} ${due.length===1?'verse is':'verses are'} ready to review.`:'Build your memory, one verse at a time.'}</h2><p>${due.length?'Remembering after a little break helps the words stay.':'Start with clues. Build up to remembering on your own.'}</p></div>${button(`${due.length?'Start review':'Pick a practice'} ${icon('arrow')}`,due.length?'review':'quick-practice','secondary')}</section><div class="journal-toolbar"><label class="search-box">${icon('search')}<input id="verse-search" type="search" placeholder="Find a verse or a word…" aria-label="Search verses" value="${e(search)}"></label><label class="topic-select">Topic <select id="topic-select">${['All','Review',...new Set(s.verses.map(v=>v.topic))].map(t=>`<option ${topic===t?'selected':''}>${e(t)}</option>`).join('')}</select></label></div><div class="verse-grid">${list.map(v=>`<article class="verse-card"><div class="section-line"><span class="topic-tag">${e(v.topic)}</span>${v.custom?`<button class="icon-btn" data-edit-verse="${e(v.id)}" aria-label="Edit ${e(v.ref)}">${icon('edit')}</button>`:icon('book')}</div><h2>${e(v.ref)}</h2><p class="verse-text">“${e(v.text)}”</p><span class="verse-source">${e(v.source)}</span><div class="verse-mastery"><div class="mastery-dots" aria-label="Mastery ${v.mastery} of 5">${Array.from({length:5},(_,i)=>`<span class="${i<v.mastery?'filled':''}"></span>`).join('')}</div><span>${masteryLabel(v.mastery)}</span></div><div class="verse-bottom"><span>${v.practiceCount?`${v.practiceCount} ${v.practiceCount===1?'practice':'practices'}`:'Ready when you are'}</span><button class="btn ghost" data-practice="${e(v.id)}">Practice ${icon('arrow')}</button></div></article>`).join('')}</div>${list.length?'':`<div class="empty-state">${icon('search')}<h2>No verses found.</h2><p>Try a different word or topic.</p>${button('Clear filters','clear-search','secondary')}</div>`}`}
export function settings(s){return heading('FOR THE GROWN-UPS','Family settings','Manage your profile, settings, and backups.')+`<div class="settings-grid"><section class="settings-card"><h2>Your explorer</h2><form id="profile-form"><label>Explorer nickname<input name="name" value="${e(s.name)}" maxlength="24" required autocomplete="off"></label><small>A nickname is plenty. No real name needed.</small>${button('Save nickname','save-profile','secondary','type="submit"')}</form><hr><h2>Make yourself comfortable</h2>${audioControls(s)}<label class="switch-row"><span><strong>Creature animations</strong><small>Turn off for a calmer experience</small></span><input id="motion-setting" type="checkbox" role="switch" ${s.settings.motion?'checked':''}></label><button class="btn outline" data-action="help">${icon('help')} How the adventure works</button></section><section class="settings-card"><h2>Your adventure, kept on this device</h2><p>There are no accounts, ads, purchases, chat, or tracking in the game. Progress is saved on this device. A backup lets you bring it to another device.</p><div class="button-row">${button(`${icon('download')} Save a backup`,'export','secondary')}${button(`${icon('upload')} Restore backup`,'import','outline')}</div><input id="import-file" type="file" accept="application/json,.json" hidden><p class="small-note">Restoring replaces this adventure. Save a backup first. Clearing browser data or deleting the app can remove your progress.</p>${s.legacyImported?'<p class="notice">Your original Scribbies save remains untouched. Compatible companions and saved verses were copied into this adventure.</p>':''}${button('Export original save','export-legacy','ghost')}<hr><h2>A fresh beginning</h2><p>Start a new adventure with a new egg. This clears the current adventure on this device.</p>${button('Start over…','reset','danger')}</section><section class="settings-card full"><div class="section-line"><h2>Learning with care</h2>${icon('shield')}</div><p>Clues and retries are always welcome. No countdowns. No lost pets. Your Scribby is safe when life gets busy. “Mastered” means a child recalled a verse independently on a later day. Grown-ups can add your family’s scriptures, translations, and quotes in the verse journal.</p><p>The chapter verses use the King James Version. The original game and its artwork are preserved in the source archive. Online trading and cloud accounts are not part of this edition.</p><div class="button-row">${button('Privacy details','privacy','outline')}${button('Back to the adventure','adventure','secondary')}</div></section></div>`}
export function practice(s,session){
 const b=activeBuddy(s),v=s.verses.find(v=>v.id===session.verseId),q=session.questions[session.index],total=session.questions.length;
 const isAdventure=session.region!==null;const sp=isAdventure?speciesById(REGIONS[session.region].encounters[session.node]):null;
 const firstStop=session.region===0&&session.node===0;
 const mode=MODES.find(m=>m.id===q?.type)||MODES[0];
 if(session.phase==='result')return resultView(s,session);
 const reading=session.phase==='read';
 return `<div class="practice-shell ${!isAdventure?'home-practice':''}"><div class="practice-top">${button(`${icon('close')} Leave`,'leave-practice','ghost')}<div class="session-progress"><span>${reading?'Read & listen':`Challenge ${session.index+1} of ${total}`}</span>${progress(reading?0:session.index,total,'','Lesson progress')}</div><span class="session-heart">${icon('heart')} ${reading?0:session.index} / ${total}</span></div><div class="practice-scene"><img src="./assets/camp-glade.webp" alt="A peaceful woodland clearing"/><div class="practice-companion">${buddyArt(b,160)}<span>${b.hatched?e(b.name):'Your egg'}</span></div>${sp&&!firstStop?`<div class="practice-encounter">${art(sp.id,155)}<span>${sp.name} is curious…</span></div>`:''}<div class="scene-story">${icon(firstStop?'sun':isAdventure?'paw':'book')}<span>${firstStop?'This practice warms your egg.':isAdventure?`A wild ${sp.name}! Share a verse and earn its trust.`:'Practice with your Scribby.'}</span></div></div><section class="learning-card"><div class="learning-heading"><span class="eyebrow">${reading?'READ & LISTEN':mode.name.toUpperCase()}</span><span class="topic-tag">${e(v.topic)}</span></div><h1>${reading?'Read or listen.':{predict:'Which word belongs here?',blanks:'Can you fill the gaps?',jumble:'Make a path with the words.',first:'Show a hint for every word.',recall:'You know more than you think.'}[q.type]}</h1><p class="learning-instruction">${reading?'Then try remembering the words.':{predict:'Tap the word that completes the verse.',blanks:'Write the missing words. Spelling help is a tap away.',jumble:'Tap the words in order. Tap a chosen word to put it back.',first:'Use the first letters to help you write the verse.',recall:'Write the verse from memory. Take all the time you need.'}[q.type]}</p><div class="verse-reference">${e(v.ref)} <span>· ${e(v.source)}</span>${button(`${icon('volume')} Listen`,'listen','ghost')}</div>${reading?`<blockquote class="reading-verse">${e(v.text)}</blockquote><div class="read-together"><span>${icon('heart')}</span><p>What do these words mean to you?<br><small>Take a moment to think or talk with a grown-up.</small></p></div>${button(`I’m ready ${icon('arrow')}`,'begin-questions','primary wide')}`:questionView(q,session,v)}<p class="learning-reassurance">${icon('sun')} No timer. Hints and retries are always available.</p></section></div>`;
}
function questionView(q,session,v){
 const answered=session.feedback?.correct;const disabled=answered?'disabled':'';
 const response=session.response||[];
 let content='';
 if(q.type==='predict')content=`<div class="cloze-verse">${q.words.map((w,i)=>q.missing.includes(i)?'<span class="word-gap">?</span>':e(w)).join(' ')}</div><div class="word-options">${q.options.map((w,i)=>`<button class="word-option ${session.selected===i?(answered?'correct':'selected'):''}" data-answer="${i}" ${disabled}>${e(w)}</button>`).join('')}</div>`;
 if(q.type==='blanks')content=`<form id="answer-form"><div class="cloze-verse input-verse">${q.words.map((w,i)=>q.missing.includes(i)?`<input class="blank-input" data-gap="${q.missing.indexOf(i)}" aria-label="Missing word ${q.missing.indexOf(i)+1}, after ${e(q.words[i-1]||'start')}" autocomplete="off" autocapitalize="none" spellcheck="false" maxlength="80" style="--letters:${Math.max(4,w.length)}" value="${e(response[q.missing.indexOf(i)]||'')}" ${disabled}>`:e(w)).join(' ')}</div></form>`;
 if(q.type==='jumble')content=`<div class="word-trail" aria-label="Your verse">${(session.order||[]).length?session.order.map(id=>`<button class="word-tile placed" data-unplace="${id}" ${disabled}>${e(q.words[id])}</button>`).join(''):'<span>Tap a word below to begin your verse…</span>'}</div><div class="word-bank">${q.tiles.map(tile=>`<button class="word-tile ${(session.order||[]).includes(tile.id)?'used':''}" data-tile="${tile.id}" ${disabled||(session.order||[]).includes(tile.id)?'disabled':''}>${e(tile.word)}</button>`).join('')}</div>`;
 if(q.type==='first'||q.type==='recall')content=`${q.type==='first'?`<div class="first-letters" aria-label="First letter hints">${q.words.map(w=>`<span>${e(w.charAt(0))}<small>${'·'.repeat(Math.min(8,w.length-1))}</small></span>`).join(' ')}</div>`:''}<form id="answer-form"><label class="recall-label" for="recall-answer">Your remembered verse</label><textarea id="recall-answer" rows="4" placeholder="Begin with the first word…" autocomplete="off" spellcheck="false" ${disabled}>${e(session.text||'')}</textarea></form>`;
 return content+`${session.feedback?`<div class="answer-feedback ${answered?'success':'retry'}" role="status">${icon(answered?'check':'heart')}<div><strong>${answered?'Correct. You’ve got it!':'Not quite. Give it another try.'}</strong><p>${answered?'One step closer.':q.type==='predict'?'Read the words around the gap for a clue.':'Check the word order and spelling. Punctuation and capitals don’t need to match.'}</p></div></div>`:''}${session.hintVisible?`<div class="hint-card"><strong>Hint</strong><p>${e(v.text)}</p></div>`:''}<div class="learning-actions">${button(`${icon('help')} Show a hint`,'hint','ghost',disabled)}${answered?button(`${session.index+1===session.questions.length?'Finish & discover':'Next step'} ${icon('arrow')}`,'next-question','primary'):q.type!=='predict'?button(`Check my words ${icon('check')}`,'check-answer','primary'):''}</div>`;
}
export function resultView(s,session){const result=session.result;const b=activeBuddy(s);return `<div class="result-page"><span class="eyebrow">PRACTICE COMPLETE</span><div class="celebration-stars" aria-label="${result.stars} stars">${[0,1,2].map(i=>`<span class="${i<result.stars?'earned':''}" style="--i:${i}">${icon('star')}</span>`).join('')}</div><h1>${result.badge?'You earned a chapter badge!':result.found?'You found a new egg!':'Practice complete!'}</h1><p>${result.found?`${speciesById(result.found).name} trusts you with an egg to raise at camp.`:result.hatchReady?'Tap, tap… your egg is ready to meet you!':'Your practice helped your Scribby grow.'}</p><div class="result-art">${result.found?eggArt(result.found,210):buddyArt(b,210)}</div>${result.badge?`<div class="badge-earned">${icon('medal')} You earned the ${result.badge} badge!</div>`:''}<div class="reward-row"><span>${icon('sparkles')}<strong>+${result.xp}</strong> XP</span><span>${icon('leaf')}<strong>+${result.coins}</strong> leaves</span><span>${icon('berry')}<strong>+1</strong> berry</span></div><div class="result-note">${icon('book')}<div><strong>${e(s.verses.find(v=>v.id===session.verseId).ref)}</strong><p>${result.stars===3?'Review another day to strengthen your memory.':'Keep practicing. You can use fewer hints next time.'}</p></div></div><div class="button-row center">${button(`${result.hatchReady?'Hatch my egg':'Back home'} ${icon('arrow')}`,result.hatchReady?'result-hatch':'finish-session','primary')}${button('Explore','result-explore','outline')}</div>${result.grown?'<p class="growth-announcement">Your buddy grew into a new life stage! Visit camp to say hello.</p>':''}</div>`}

export function audioControls(s){return `<div class="audio-controls"><label class="switch-row"><span><strong>Music</strong><small>Exploring and camp themes</small></span><input id="music-setting" type="checkbox" role="switch" ${s.settings.music?'checked':''}></label><label class="audio-slider" for="music-volume">Music volume <output id="music-volume-value">${Math.round(s.settings.musicVolume*100)}%</output><input id="music-volume" type="range" min="0" max="100" step="5" value="${Math.round(s.settings.musicVolume*100)}"></label><label class="switch-row"><span><strong>Sound effects</strong><small>Scribby voices and celebrations</small></span><input id="sound-setting" type="checkbox" role="switch" ${s.settings.sound?'checked':''}></label><label class="audio-slider" for="effects-volume">Effects volume <output id="effects-volume-value">${Math.round(s.settings.effectsVolume*100)}%</output><input id="effects-volume" type="range" min="0" max="100" step="5" value="${Math.round(s.settings.effectsVolume*100)}"></label>${button('Hear your Scribby','preview-voice','outline')}<p class="small-note">Music starts after your first tap. It gets quieter during practice and fades out for read-aloud.</p></div>`}
